In [19]:
import numpy as np

In [20]:
#리스트와 넘파이 차이 
list_ = [1,2,3]
print(list_)

[1, 2, 3]


In [21]:
#array : 배열 
#np.array(리스트)
np.array([1,2,3])

array([1, 2, 3])

In [22]:
arr = np.array([1,2,3])
print(arr) #리스트와 같이 출력됨(',' 없음, 콤마 상실 ) 배열
print(arr[0]) #리스트와 같이 indexing됨 >> 순서가 있다! 
print(arr[-1])

[1 2 3]
1
3


In [23]:
#왜 넘파이를 배울까

#리스트 + 리스트 >> 연장됨(크기가 커짐)
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [24]:
c =[1,2,3] + [4,5,6]
print(c)
print(len(c))

[1, 2, 3, 4, 5, 6]
6


In [25]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

arr_a + arr_b  #같은 위치에 있는 원소(element)끼리 더해짐 (연산 가능) 

array([5, 7, 9])

In [26]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) #2차원 배열 
#>> np.array([arr_1,arr_2,arr_3])
print(a.shape)

(3, 3)


In [27]:
arr_e = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_e[-1][-1]

9

넘파이 배열 속성

In [28]:
arr_e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_e)

#배열구조
#(3,3) : 3개의 리스트에 각각 3개의 값이 있다 ! 
print(arr_e.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [29]:
arr_a = np.array([1,2,3])
print(arr_a)
print(arr_a.shape) #1차원 원소가 3개 있다 

[1 2 3]
(3,)


In [30]:
arr_f = np.array([[1],[2],[3]])
print(arr_f)
print(arr_f.shape) #2차원 3개의 행에 열 1개의 배열

[[1]
 [2]
 [3]]
(3, 1)


In [31]:
#배열의 차원 수 
print(arr_a.ndim) #1차원
print()
print(arr_f.ndim) #2차원 

#ndim : 차원수를 알려줌


1

2


In [32]:
arr_f #배열안에 리스트

array([[1],
       [2],
       [3]])

In [33]:
print(arr_f) #배열 

[[1]
 [2]
 [3]]


In [34]:
#요소의 자료형 
#dtype : 데이터 타입 
arr_f.dtype

dtype('int32')

In [35]:
#요소의 한 개의 크기 
#int : 4바이트 
arr_f.itemsize

4

In [36]:
#전체 요소의 크기 
arr_f.size

3

In [37]:
#zeros(), eye(), ones() 함수 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.ones((3,4)).dtype

dtype('float64')

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#arange() : array + range 배열의 범위
#np.arange(start, stop, step)

np.arange(5)

array([0, 1, 2, 3, 4])

In [42]:
print(np.arange(5)) #배열

[0 1 2 3 4]


In [43]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [44]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [45]:
#linspace () 함수
#0부터 10까지 동등하게 10개의 구간을 나눠라
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [46]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [47]:
#2개의 배열 합치기
np.array([[1,2],[3,4]])

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [48]:
concat_0 = np.concatenate((x,y)) #한 배열로 합치기 
print(concat_0)
print(concat_0.shape)

#default: axis=0 행으로 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [49]:
concat_1 = np.concatenate((x,y), axis = 1) #열로 합침 
print(concat_1)
print(concat_1.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [50]:
#vstack, hstack
#1. vstack : v(vertical 수직의) + stack(쌓아 올리다)
np.vstack((x,y))
print()
print(np.concatenate((x,y), axis=0) )


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
#2. hstack : h(horizontal 수평선의) + stack(쌓아 올린다)
np.hstack((x,y))
print()
print(np.concatenate((x,y), axis=1) )


[[1 2 5 6]
 [3 4 7 8]]


reshape(****) 차원을 변화

In [52]:
a = np.arange(12)
print(a.shape) #1차원, (행은 1개만 있음)

(12,)


In [53]:
#reshape() : 형태를 변경
#1차원 >> 2차원
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
dim_2 = a.reshape(3,4) #2차원
dim_2.shape

(3, 4)

In [56]:
a.reshape(3,-1)
#형태를 행은 3개를 만들고 열은 전췌 원소를 고려해서 끝(-1)에 맞춰 생성 (자동완성)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
temp = np.arange(11)


In [59]:
#temp.reshape(3,-1) 
#ValueError: cannot reshape array of size 11 into shape (3,newaxis)
#원소의 개수가 안맞으면 에러 발생 

In [60]:
#배열 분할하기

arr =np.arange(30).reshape(-1,10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [61]:
np.split(arr,[3],axis=1) #행세열가

[array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]]),
 array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19],
        [23, 24, 25, 26, 27, 28, 29]])]

In [62]:
arr1, arr2 = np.split(arr,[3],axis=1)
print(arr1)
print(arr2)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[ 3  4  5  6  7  8  9]
 [13 14 15 16 17 18 19]
 [23 24 25 26 27 28 29]]


In [63]:
#배열(array)에 새로운 축 추가하기 

a = np.array([1,2,3,4,5,6])

print(a)
print()
print(a.shape)

[1 2 3 4 5 6]

(6,)


In [64]:
a1 = a[np.newaxis, :]
print(a1)
a1.shape # 1*6행렬(2차원)

[[1 2 3 4 5 6]]


(1, 6)

In [65]:
a2 = a[:, np.newaxis]
print(a2)
print()
print(a2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

(6, 1)


In [66]:
#인덱스와 슬라이싱

np.array([18,19,25,30,28])

array([18, 19, 25, 30, 28])

In [67]:
ages = np.array([18,19,25,30,28])
#인덱싱
ages[2] 

25

In [68]:
#슬라이싱
print(ages[1:3])
print(ages[:-2])



[19 25]
[18 19 25]


In [69]:
#논리적 인덱싱 

ages>20 # 비교연산자 

array([False, False,  True,  True,  True])

In [70]:
condition = (ages > 20)
ages[condition]

array([25, 30, 28])

In [71]:
ages[ (ages > 20)]

array([25, 30, 28])

In [72]:
#2차원 배열 인덱싱 

np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])

print(a[0][2])

a[0,2]


[1 2 3]
3


3

In [74]:
a[0,0] = 12
print(a)
print(a.shape)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]
(3, 3)


In [75]:
a[0:2]
print(a)
print(a[0:2].shape)


[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]
(2, 3)


In [76]:
print(a)

a[0:2, 1:3] #행 0-1행 / 1-2열 추출 

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


array([[2, 3],
       [5, 6]])

In [77]:
a[::2, ::2] #2칸 간격의 행열 가져오기

array([[12,  3],
       [ 7,  9]])

넘파이 연산

In [78]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[1,1],[1,1],[1,1]])

In [79]:
print(arr1)
print()
print(arr2)


[[1 2]
 [3 4]
 [5 6]]

[[1 1]
 [1 1]
 [1 1]]


In [80]:
result = arr1 + arr2 

result

array([[2, 3],
       [4, 5],
       [6, 7]])

In [81]:
#cf) list + list

a = [1,2,3,4]
b = [5,6,7,8]
a+b 

[1, 2, 3, 4, 5, 6, 7, 8]

In [82]:
a.extend(b)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8]


In [83]:
#브로드 캐스팅

np.array([1,2,3])

array([1, 2, 3])

In [84]:
miles = np.array([1,2,3])

miles * 1.6

array([1.6, 3.2, 4.8])

In [85]:
miles[0] * 10

10

In [86]:
#리스트는 연산 안됨 
#[1,2,3] * 1.6
#TypeError: can't multiply sequence by non-int of type 'float'

In [87]:
#넘파이 곱셈

arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[2,2],[2,2],[2,2]])

result = arr1 * arr2
print(arr1)
print()
print(arr2)
print()
print(result)


[[1 2]
 [3 4]
 [5 6]]

[[2 2]
 [2 2]
 [2 2]]

[[ 2  4]
 [ 6  8]
 [10 12]]
