In [1]:
import numpy as np

In [12]:
arr1 = np.array([1,2,3])
print(arr1)

print(type(arr1))
print(arr1.shape) #1차원


[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [13]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print(type(arr2))
print(arr2.shape) #2차원 2행리스트에 3개의 값 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [14]:
arr3 = np.array([[1,2,3]])
print(arr3)

print(type(arr3))
print(arr3.shape)

[[1 2 3]]
<class 'numpy.ndarray'>
(1, 3)


In [15]:
#ndim : 몇차원인지 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


1
2
2


In [16]:
#arange : array + range 

np.arange(3)

array([0, 1, 2])

In [17]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [18]:
#넘파이 배열 초기화 

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
a = np.ones((3,4))


<class 'numpy.ndarray'>


In [24]:
#zeros_like() : 동일한 배열 값에 0으로 채워진 배열 생성 
np.zeros_like(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
#eye() : 항등 행렬 
# A : A * I = A
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
A = np.array([[2,3,1,5],
              [8,1,3,4],
              [5,6,7,8],
              [1,2,3,4]])

print(A)
print()
I = np.eye(4)
print(I)
print()
print(A@I)

[[2 3 1 5]
 [8 1 3 4]
 [5 6 7 8]
 [1 2 3 4]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[2. 3. 1. 5.]
 [8. 1. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 3. 4.]]


In [25]:
b = np.array([[1,2,3],[4,5,6]])

print(b)


[[1 2 3]
 [4 5 6]]


In [26]:
np.zeros_like(b)

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
#np.full, np.random and 

#np.full(배열크기지정, 채울값)

print(np.full((4,5),9)) #배열 크기 만큼 9로 채워넣어라
print(np.full((4,5),5))

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [42]:
#np.random()

print(np.random.seed(100))
print()
print(np.random.random((3,4)))  #0~1 사이 난수 생성 / 튜플형태 (3,4)(한 번만 전달받음)
print()
print(np.random.rand(3,4,2)) #0~1 사이 난수 생성 / 여러 개 인자를 받아 차원 생성 
print()
print(np.random.randn(3,4)) # 평균0, 표준편차 -1  
print()
print(np.random.randint(1,5)) #랜덤한 숫자 1개만 생성 

None

[[0.54340494 0.27836939 0.42451759 0.84477613]
 [0.00471886 0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195 0.20920212]]

[[[0.18532822 0.10837689]
  [0.21969749 0.97862378]
  [0.81168315 0.17194101]
  [0.81622475 0.27407375]]

 [[0.43170418 0.94002982]
  [0.81764938 0.33611195]
  [0.17541045 0.37283205]
  [0.00568851 0.25242635]]

 [[0.79566251 0.01525497]
  [0.59884338 0.60380454]
  [0.10514769 0.38194344]
  [0.03647606 0.89041156]]]

[[ 0.18451869  0.9370822   0.73100034  1.36155613]
 [-0.32623806  0.05567601  0.22239961 -1.443217  ]
 [-0.75635231  0.81645401  0.75044476 -0.45594693]]

4


In [49]:
#넘파이 배열 크기 변형 

np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
arr = np.arange(12)
print(arr)

print(len(arr))
print()
arr2 = arr.reshape(3,-1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [55]:
arr.reshape(4,-1,order='F') #값을 열부터 채워넣음

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(-1,5)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [60]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 5)


In [61]:
arr3 = np.arange(12)
print(arr3)

arr4 = arr3.reshape(2,3,2)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [62]:
arr5 = arr3.reshape(2,3,2, order='F')
print(arr5)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [63]:
print(arr5.ndim)
print(arr5.shape)

3
(2, 3, 2)


In [64]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
arr2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#넘파이 배열 데이터 추출하기 

#1) indexing 

np.arange(1,10)

arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [67]:
print(arr1[2])
print(arr1[-2])


3
8


In [77]:
arr2 = arr1.reshape(3,3)
print(arr2)
print()

print(arr2[0,0])
print(arr2[-1,-2])
print(arr2[-1,:-1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
8
[7 8]


In [83]:
print(arr1)
print()

arr2 =arr1[0:3]
print(arr2)
print()

arr3 = arr2[1:]
print(arr3)
print()
arr4 = arr1.reshape(3,3)
print(arr4)

[1 2 3 4 5 6 7 8 9]

[1 2 3]

[2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
#슬라이싱
print(arr4)
print()

print(arr4[1:3,:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5 6]
 [7 8 9]]


전치 행렬 

In [91]:
#내적 (dpt [product])

arr1 =np.array([[1,2,3],[4,5,6]]) # (2,3)

arr2 = np.array([[7,8],[9,10],[1,2]]) # (3,2)

arr3 = np.array([[7,8,1],[9,10,2]]) # (2,3)


In [89]:
arr1 @ arr2 #행렬의 곱 (2,3) @ (3,2)

array([[28, 34],
       [79, 94]])

In [90]:
np.dot(arr1,arr2) # @이랑 같은 식 

array([[28, 34],
       [79, 94]])

In [93]:
arr1 @ arr3.T
# arr3.T 행렬을 바꿈 
# np.transpose(arr3) 랑 같음  

array([[26, 35],
       [74, 98]])

In [95]:
np.dot(arr1,arr3.T)

array([[26, 35],
       [74, 98]])

In [98]:
#넘파이 이용, 기술 통계 

x = np.array([11,12,13,-43,34,66,42])
len(x)

7

In [101]:
print(np.mean(x)) #평균
print(np.var(x)) #분산 (std **2)
print(np.std(x)) #표준편차


19.285714285714285
993.6326530612245
31.52193923382926


In [105]:
print(x)
print()

print(np.max(x))
print()

print(np.min(x))
print()

print(np.median(x))
print()



[ 11  12  13 -43  34  66  42]

66

-43

13.0


In [106]:
x.sort()
x

array([-43,  11,  12,  13,  34,  42,  66])

In [112]:
#사분위수 
print(np.percentile(x, 25))
print(np.percentile(x, 50))
print(np.percentile(x, 75))


11.5
13.0
38.0
