In [1]:
#배열 만들기 

list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
print(np.array([3,1.4,2,3,4.5]))

#넘파이의 array는 단일 데이터 타입 
#정수, 실수 >> 실수 변경됨 

[3.  1.4 2.  3.  4.5]


In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
print(np.array([1,2,3,4]))
print(np.array([1,2,3,4],dtype=float))
#dtype 옵션 : data type 명시

print()
arr = np.array([1,2,3,4],dtype=float)
print(arr)
print(arr.dtype)
print(arr.astype(int))  #astype : 타입변경 float --> int 

[1 2 3 4]
[1. 2. 3. 4.]

[1. 2. 3. 4.]
float64
[1 2 3 4]


In [9]:
#np.zeros()
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#np.ones()
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#np.arange(start,end, step)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
#np.linspace(start,end, 나눌 개수) : 엔빵
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
#난수 활용, 배열 만들기 

np.random.random((2,2))

array([[0.85057756, 0.53962904],
       [0.38994755, 0.79296561]])

In [15]:
#np.random.random 과 np.random.rand 차이 

np.random.rand(2,2)

array([[0.92699328, 0.79020741],
       [0.23127469, 0.6369915 ]])

In [16]:
#np.random()

print(np.random.seed(100))
print()
print(np.random.random((3,4)))  #0~1 사이 난수 생성 / 튜플형태 (3,4)(한 번만 전달받음)
print()
print(np.random.rand(3,4,2)) #0~1 사이 난수 생성 / 여러 개 인자를 받아 차원 생성 
print()
print(np.random.randn(3,4)) # 평균0, 표준편차 -1  
print()
print(np.random.randint(1,5)) #랜덤한 숫자 1개만 생성

None

[[0.54340494 0.27836939 0.42451759 0.84477613]
 [0.00471886 0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195 0.20920212]]

[[[0.18532822 0.10837689]
  [0.21969749 0.97862378]
  [0.81168315 0.17194101]
  [0.81622475 0.27407375]]

 [[0.43170418 0.94002982]
  [0.81764938 0.33611195]
  [0.17541045 0.37283205]
  [0.00568851 0.25242635]]

 [[0.79566251 0.01525497]
  [0.59884338 0.60380454]
  [0.10514769 0.38194344]
  [0.03647606 0.89041156]]]

[[ 0.18451869  0.9370822   0.73100034  1.36155613]
 [-0.32623806  0.05567601  0.22239961 -1.443217  ]
 [-0.75635231  0.81645401  0.75044476 -0.45594693]]

4


In [20]:
np.random.normal(0,1,(2,2)) #정규분포 (2,2) 튜플형태로 매개변수 받음
#np.random.normal(평균, 표준편차, 매개변수(튜플))

array([[-1.00805248,  0.35482923],
       [-0.70266818,  0.11345113]])

In [21]:
np.random.randn(2,3)

array([[-1.0411337 , -0.68659935, -2.55944758],
       [ 0.94631055,  0.79067165,  0.68000189]])

In [44]:
np.random.randint(0,10,(2,2))
#0~9까지 랜덤 숫자 1개를 불러와 (2,2) 구조로 생성

array([[6, 4],
       [8, 6]])

In [43]:
#배열의 기초 

np.random.randint(10, size=(3,4))

array([[7, 3, 0, 2],
       [5, 1, 1, 0],
       [3, 6, 7, 3]])

In [27]:
x = np.random.randint(10, size=(3,4))
print(x.ndim) #2차원 
print(x.shape) #형태 (3,4)
print(x.size) #크기(원소 개수)
print(x.dtype) #데이터 타입 

2
(3, 4)
12
int32


In [28]:
#indexing 과 slicing

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
a =np.arange(7)
print(a[3])
print(a[-3])



3
4


In [40]:
#slicing 

print(a)
print()
print(a[1:4])
print()
print(a[1:])
print()
print(a[::2])
print()
print(a[::-1]) #역순 출력!

[0 1 2 3 4 5 6]

[1 2 3]

[1 2 3 4 5 6]

[0 2 4 6]

[6 5 4 3 2 1 0]


In [51]:
#reshape(형태 변경) ******

x = np.arange(8)
print(x)
print()
print(x.shape)
print()

x2 = x.reshape((2,4))
print(x2.shape)

[0 1 2 3 4 5 6 7]

(8,)

(2, 4)


In [56]:
#concatente 

#이어 붙이기 >> array이어 붙임 

x = np.array([0,1,2])
y = np.array([3,4,5])

np.concatenate([x,y])


array([0, 1, 2, 3, 4, 5])

In [68]:
#concatenate >> axis 축 기준 이어 붙이기 

m = np.arange(4).reshape(2,2)
print(m)
r = np.concatenate([m,m], axis = 0 ) # 행의 열 방향
print(r)
print()
c = np.concatenate([m,m], axis = 1 ) # 열의 행 방향
print(c)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1 0 1]
 [2 3 2 3]]


In [71]:
#나누기 split
np.arange(16).reshape(4,4)

m = np.arange(16).reshape(4,4)
print(m)
print()
np.split(m,[3], axis=0)#배열이 2가지 생성됨

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [73]:
np.split(m,[3], axis=1)

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [74]:
m3, m4 = np.split(m,[3], axis=1)

print(m3)
print()
print(m4)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


넘파이 연산

In [88]:
#array의 모든 원소에 5를 더하는 함수 생성 

def sum_5(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = values[i] + 5 
    return output 

values = np.random.randint(1, 10, size=5)

print(values)
print()
print(sum_5(values))
        

[8 1 9 9 4]

[13.  6. 14. 14.  9.]


In [87]:
#loop vs numpy 

big_arr = np.random.randint(1, 10, size=100000)

sum_5(big_arr)

array([ 7.,  8., 13., ..., 11.,  6., 14.])

In [89]:
big_arr + 5  #브로드캐스팅 되어 계산 

array([ 7,  8, 13, ..., 11,  6, 14])

In [90]:
#기본 연산

x = np.arange(4)

print(x+5)
print(x-5)
print(x/5)
print(x*5)


[5 6 7 8]
[-5 -4 -3 -2]
[0.  0.2 0.4 0.6]
[ 0  5 10 15]


In [109]:
#행렬 간 연산 

y = np.arange(4).reshape((2,2))

z = np.random.randint(10, size=(2,2))


print(y)
print()
print(z)
print()

print(y+z)
print()

print(y*z)



[[0 1]
 [2 3]]

[[4 8]
 [1 8]]

[[ 4  9]
 [ 3 11]]

[[ 0  8]
 [ 2 24]]


In [106]:
#집계함수 

x = np.arange(8).reshape((2,4))

print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))


28
0
7
3.5


In [111]:
#axis 사용, 집계하기
print(x)
print()
print(np.sum(x, axis=0)) #행의 열방향 
print()
print(np.sum(x, axis=1)) #열의 행방향 


[[0 1 2 3]
 [4 5 6 7]]

[ 4  6  8 10]

[ 6 22]


In [114]:
#마스킹(masking) 연산 (조건 연산자 >> True, False)

x = np.arange(5)

print(x)
print()
print(x < 3)
print()
print(x > 5)


[0 1 2 3 4]

[ True  True  True False False]

[False False False False False]


In [116]:
x[x<3] #특정 조건을 갖는 값을 가져올때 

array([0, 1, 2])

In [117]:
#리스트를 튜플로

tuple(x[x<3])

(0, 1, 2)